steps:
  # Install dependencies
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['ci']

  # Build the application
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Build and push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nitro-app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nitro-app:$COMMIT_SHA']

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/nitro-app:$COMMIT_SHA'